# Generated by Django 5.2 on 2025-04-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='video_url',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
