# Generated by Django 5.2 on 2025-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_car_brand_car_rating_car_video_url_user_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.TextField(),
        ),
    ]
